version: '3.8'
services:
    app:
        build: 
            context: .
            dockerfile: ./Dockerfile
        ports:
            - ${APP_EXTERNAL_PORT}:${APP_INTERNAL_PORT}
        restart: unless-stopped
        depends_on:
            - postgres
        env_file: .env
        networks:
            - backend

    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - ${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}
        networks:
            - backend
        restart: unless-stopped

volumes:
    pgdata:
networks:
    backend:
        driver: bridge
